Remove unecessary creation of symlinks to binaries, and general tidy up.

diff --git a/check-passphrase b/check-passphrase
--- a/check-passphrase
+++ b/check-passphrase
@@ -2,29 +2,68 @@
 # This script allows you to check your wallet passphrase without exposing it to
 # the screen or adding it to the BASH history.
 #
-# Obfuscation alone is not good security.
+# Remember that obfuscation alone is not good security.
 # ------------------------------------------------------------------------------
 set -o nounset
 set -o errexit
 
+THIS=$(readlink -f ${BASH_SOURCE[0]})
 PROJECT_ROOT=$(dirname $THIS)
-. $PROJECT_ROOT/lib/setup-cold-wallet
+. ${PROJECT_ROOT}/lib/config
+. ${PROJECT_ROOT}/lib/select-coin
+. ${PROJECT_ROOT}/lib/setup-binaries
+. ${PROJECT_ROOT}/lib/setup-cold-wallet
 
-function get_passphrase() {
+echo -e ${YELLOW}
+echo "-------------------------------------------------------------------------"
+echo "ONLY RUN IN AN OFFLINE TAILS SESSION!"
+echo "-------------------------------------------------------------------------"
+echo -e ${NC}
+
+read -p "Set up Binaries? [y/N]" PROCEED_BINARIES
+case $PROCEED_BINARIES in
+  [Yy]* )
+    select_coin
+    setup_binaries
+  ;;
+  [Nn]* )
+    echo "Proceeding without setup of binaries..."
+    select_coin
+  ;;
+  * ) echo "Please answer yes or no.";;
+esac
+
+read -p "Do you wish to set up a cold wallet? [y/N]" PROCEED
+case $PROCEED in
+  [Yy]* )
+    select_cold_wallet
+    copy_wallet
+  ;;
+  [Nn]* )
+    echo "END"
+  ;;
+  * ) echo "Please answer yes or no.";;
+esac
+
+# Silently read the passphrase
+# ------------------------------------------------------------------------------
+function get_passphrase {
   echo "Please enter the wallet passphrase:"
   read -s WALLET_PASSPHRASE
 }
 
-function check_passphrase() {
-  bitcoin-cli -wallet=cold-wallet.dat -rpcwait walletpassphrase "${WALLET_PASSPHRASE}" 600
-  if [[ $? -eq 0  ]]; then
-    echo -e ${YELLOW}
-    echo "+-------------------------------------------------------------------+"
-    echo "| You entered the CORRECT passphrase.                               |"
-    echo "+-------------------------------------------------------------------+"
+# Unlock the wallet
+# ------------------------------------------------------------------------------
+function run_passphrase {
+  ${COIN}-cli -wallet=cold-wallet.dat -rpcwait walletpassphrase "${WALLET_PASSPHRASE}" 600 && rc=$? || rc=$?
+  if [[ $rc -eq 0  ]]; then
+    echo -e ${GREEN}
+    echo ""
+    printf "  SUCCESS: You entered the CORRECT passphrase."
+    echo ""
     echo -e ${NC}
     echo "Locking wallet..."
-    bitcoin-cli walletlock
+    ${COIN}-cli walletlock
     if [[ $? -eq 0  ]]; then
       echo "Wallet is LOCKED."
     else
@@ -32,14 +71,34 @@ function check_passphrase() {
     fi
   else
     echo -e ${RED}
-    echo "+-------------------------------------------------------------------+"
-    echo "| You entered an INCORRECT passphrase.                              |"
-    echo "+-------------------------------------------------------------------+"
+    echo ""
+    printf "  WARNING: You entered an INCORRECT passphrase."
+    echo ""
     echo -e ${NC}
   fi
 }
+
+# Wrapper function
+# ------------------------------------------------------------------------------
+function check_passphrase {
+
+  get_passphrase
+  run_passphrase
+
+  read -p "Do you want to try again with this wallet? [y/N]" REPEAT
+  case $REPEAT in
+    [Yy]* )
+      check_passphrase
+    ;;
+    [Nn]* )
+      echo "Finished"
+    ;;
+    * ) echo "Please answer yes or no.";;
+  esac
+
+}
+
 open_port
-start_bitcoind
-get_passphrase
+start_daemon
 check_passphrase
-bitcoin-cli stop
+${COIN}-cli stop
diff --git a/dumpprivkeys b/dumpprivkeys
--- a/dumpprivkeys
+++ b/dumpprivkeys
@@ -21,39 +21,30 @@ NAME=$0
 CUSTOM_DATA_DIR='false'
 
 read -p "Set up Binaries? [y/N]" PROCEED_BINARIES
-
 case $PROCEED_BINARIES in
   [Yy]* )
-    select_coin
-    setup_binaries
+  select_coin
+  setup_binaries
   ;;
   [Nn]* )
-    echo "Proceeding without setup of binaries..."
-    select_coin
+  echo "Proceeding without setup of binaries..."
+  select_coin
   ;;
   * ) echo "Please answer yes or no.";;
 esac
 
 read -p "Do you wish to set up a cold wallet? [y/N]" PROCEED
-
 case $PROCEED in
   [Yy]* )
-    select_cold_wallet
-    copy_wallet
+  select_cold_wallet
+  copy_wallet
+  WALLET_NAME=$(basename "${WALLET_FILE}")
   ;;
   [Nn]* )
-    echo "END"
+  echo "END"
   ;;
   * ) echo "Please answer yes or no.";;
 esac
-
-# Silently read the passphrase
-# ------------------------------------------------------------------------------
-function get_passphrase {
-  echo "Please enter the wallet passphrase:"
-  read -s WALLET_PASSPHRASE
-}
-
 
 # Unlock the wallet.
 # ------------------------------------------------------------------------------
@@ -61,32 +52,49 @@ function unlock {
   echo "Please enter the wallet passphrase: "
   read -s WALLET_PASSPHRASE
   echo "Unlocking wallet..."
-   ${COIN}-cli -wallet=cold-wallet.dat -rpcwait walletpassphrase "${WALLET_PASSPHRASE}" 600
+  ${COIN}-cli -wallet=cold-wallet.dat -rpcwait walletpassphrase "${WALLET_PASSPHRASE}" 600
 }
 
 # Use bitcoin-cli dumpwallet command to output private keys.
 # ------------------------------------------------------------------------------
 function dump_keys {
   DATE=$(date "+%Y-%m-%d-%H:%M:%S")
-  DUMP_DIR=~/${COIN}-dumpwallet-${DATE}
+  DUMP_DIR=~/${COIN}-dumpwallet-${WALLET_NAME}
+
   mkdir -p ${DUMP_DIR}
-  WALLET_DUMP=${DUMP_DIR}/wallet-dump  
-  ${COIN}-cli dumpwallet ${WALLET_DUMP}
+  echo "Select a File that contains a list of public addresses to backup."
+  PUB_ADDRESSES_LIST=$(zenity --file-selection --title="Select a file that contains a list of public addresses to be dumped." --filename=~/)
+  case $? in
+    0)
+    echo "\"${PUB_ADDRESSES_LIST}\" selected.";;
+    1)
+    echo "No file selected.";;
+    -1)
+    echo "An unexpected error has occurred.";;
+  esac
+
+  echo "Key Backups: ${WALLET_NAME}, ${DATE}" > ${DUMP_DIR}/readme.md
+  echo "============================================" >> ${DUMP_DIR}/readme.md
+  echo "This directory contains private keys for the following public addresses:" >> ${DUMP_DIR}/readme.md
+
+  echo "Enter a passphrase for GPG encryption:"
+  read -s GPG_PASS
+
+  PUB_ADDRESSES="$(< ${PUB_ADDRESSES_LIST})"
+
+  for PUB in $PUB_ADDRESSES; do
+    PRIV=$(${COIN}-cli dumpprivkey ${PUB})
+    echo "${PUB}" >> ${DUMP_DIR}/readme.md
+    echo "${PRIV}" > ${DUMP_DIR}/${PUB}
+    gpg --armor --output ${DUMP_DIR}/${PUB}.gpg --batch --passphrase ${GPG_PASS} --symmetric ${DUMP_DIR}/${PUB}
+    shred -vfzu ${DUMP_DIR}/${PUB}
+
+  done
+
   ${COIN}-cli walletlock
   ${COIN}-cli stop
-  echo "Your dumped wallet:"
-  echo "${WALLET_DUMP}"
-}
-
-# Use GPG to symmetrically encrypt the dumped wallet data files, then securely
-# delete the originals using the shred utility. Use a high-quality passphrase.
-# ------------------------------------------------------------------------------
-function encrypt_keyfiles_and_cleanup {
-  echo "${NAME} - Encrypting wallet outputs..."
-  gpg --armor --output ${WALLET_DUMP}.gpg --symmetric ${WALLET_DUMP}
-  echo "${NAME} - Securely deleting the plaintext wallet dumps using shred..."
-  shred -vfzu ${WALLET_DUMP}
-  echo "Note that if you open the encrypted files in TAILS, they will be automatically decrypted."
+  echo "Your dumped keys:"
+  echo "${DUMP_DIR}"
 }
 
 # Execute
@@ -98,7 +106,6 @@ case $YN in
   start_daemon
   unlock
   dump_keys
-  encrypt_keyfiles_and_cleanup
   ;;
   [Nn]* )
   echo "END."
